permalink: pretty
theme: jekyll_patternbot

patternbot:
  title: "Breaking Bread"
  description: |
    Artisanal online bread shop!
  font_url: "https://use.typekit.net/dzi0tye.css"
  colors:
    background: "--color-primary-light"
    accent: "--color-primary-dark"
    patterns:
      brand.logos: "--color-primary-light"
  rationales:
    typefaces.primary: |
      Garamond was slected because it's a very cohesive typeface. Georgia is to be used for all body copy and most situations.
    typefaces.secondary: |
      Proxima Nova is only to be used for highlighting text headings, buttons, banner, etc.
    colors.primary: |
      The primary colours is modern and clean, continuing with the each tones, and should be used for backgrounds.
    colors.secondary: |
      The secondary colours are more neautral. They should be used in text and foregrounds.
