permalink: pretty
theme: jekyll_patternbot

patternbot:
  title: "Dino Rescue"
  description: |
    A small local dinosaur rescue organization specializing in herbivores. Dinos are in danger and we need to save them all!
  font_url: "https://use.typekit.net/pfq7ikh.css"
  rationales:
    typefaces.primary: |
    Georgia was slected because it's a classic font-for classic creatures. Georgia is to be used for all body copy and most situations.

    typefaces.secondary: PT Sans NArrow is only to be used for highlighting text: headings, buttons, banner, etc.

    colors.primary: |
    The primary colours represent herbivores & plants & greenery. They should be used in text and foregrounds.

    colors.secondary:
