permalink: pretty
theme: jekyll_patternbot

patternbot:
  font_url: "https://use.typekit.net/pfq7ikh.css"
  title: "Dino Rescue"
  description: |
  A small local dinosaur rescue organization specializing in herbivores. Dinos are in danger and we need to save them all!
